version: '3'
services:
  isaacsim-template:
    image: isaacsim-template:main
    build:
      context: ../
      dockerfile: ./binder/Dockerfile
    stdin_open: true
    tty: true
    # set group id of the host machine, so we can edit contents of the mounted volumes in the jupyterlab
    user: "jovyan:${GID}"
    # user: root
    working_dir: /home/jovyan/work
    # entrypoint: /home/jovyan/work/binder/entrypoint.sh
    command: jupyter lab --allow-root --NotebookApp.token='' --no-browser --ip=0.0.0.0
    ports:
      - 8888:8888
    volumes:
      - ../:/home/jovyan/work:rw
      # - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /usr/share/vulkan/icd.d/:/etc/vulkan/icd.d
      - ${PWD}/dev-tools:/mnt/dev-tools:rw
      - ${PWD}/dev-tools/isaacsim-cache/5.1/cache/kit:/isaac-sim/kit/cache:rw
      - ${PWD}/dev-tools/isaacsim-cache/5.1/cache/ov:/root/.cache/ov:rw
      - ${PWD}/dev-tools/isaacsim-cache/5.1/cache/pip:/root/.cache/pip:rw
      - ${PWD}/dev-tools/isaacsim-cache/5.1/cache/glcache:/root/.cache/nvidia/GLCache:rw
      - ${PWD}/dev-tools/isaacsim-cache/5.1/cache/computecache:/root/.nv/ComputeCache:rw
      - ${PWD}/dev-tools/isaacsim-cache/5.1/logs:/root/.nvidia-omniverse/logs:rw
      - ${PWD}/dev-tools/isaacsim-cache/5.1/data:/root/.local/share/ov/data:rw
      - ${PWD}/dev-tools/isaacsim-cache/5.1/documents:/root/Documents:rw
    environment:
      # - DISPLAY
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ACCEPT_EULA="YES"
      - PRIVACY_CONSENT="YES"
      - OMNI_KIT_ACCEPT_EULA="YES"
      - OMNI_KIT_ALLOW_ROOT="1"
      - DEV_TOOLS_PATH="/mnt/dev-tools"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]